// Mocks generated by Mockito 5.4.4 from annotations
// in cinco_minutos_meditacao/test/modules/meditometer/screens/meditometer/meditometer_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cinco_minutos_meditacao/modules/meditometer/screens/meditometer/meditometer_contract.dart'
    as _i4;
import 'package:cinco_minutos_meditacao/modules/meditometer/screens/meditometer/meditometer_model.dart'
    as _i2;
import 'package:cinco_minutos_meditacao/modules/meditometer/screens/meditometer/meditometer_presenter.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMeditometerModel_0 extends _i1.SmartFake
    implements _i2.MeditometerModel {
  _FakeMeditometerModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MeditometerPresenter].
///
/// See the documentation for Mockito's code generation for more information.
class MockMeditometerPresenter extends _i1.Mock
    implements _i3.MeditometerPresenter {
  MockMeditometerPresenter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set view(_i4.MeditometerViewContract? _view) => super.noSuchMethod(
        Invocation.setter(
          #view,
          _view,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.MeditometerModel get model => (super.noSuchMethod(
        Invocation.getter(#model),
        returnValue: _FakeMeditometerModel_0(
          this,
          Invocation.getter(#model),
        ),
      ) as _i2.MeditometerModel);

  @override
  set model(_i2.MeditometerModel? _model) => super.noSuchMethod(
        Invocation.setter(
          #model,
          _model,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onOpenScreen() => super.noSuchMethod(
        Invocation.method(
          #onOpenScreen,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> initPresenter() => (super.noSuchMethod(
        Invocation.method(
          #initPresenter,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateImageProfile() => (super.noSuchMethod(
        Invocation.method(
          #updateImageProfile,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void goToAbout() => super.noSuchMethod(
        Invocation.method(
          #goToAbout,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
