// Mocks generated by Mockito 5.4.4 from annotations
// in cinco_minutos_meditacao/test/modules/meditate/guided_meditation_program/guided_meditation_program_presenter_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:auto_route/auto_route.dart' as _i6;
import 'package:cinco_minutos_meditacao/core/routers/app_router.dart' as _i5;
import 'package:cinco_minutos_meditacao/modules/meditate/screens/guided_meditation_program/guided_meditation_program_contract.dart'
    as _i7;
import 'package:cinco_minutos_meditacao/modules/meditate/screens/guided_meditation_program/guided_meditation_program_repository.dart'
    as _i3;
import 'package:cinco_minutos_meditacao/shared/models/error.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCustomError_0 extends _i1.SmartFake implements _i2.CustomError {
  _FakeCustomError_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GuidedMeditationProgramRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGuidedMeditationProgramRepository extends _i1.Mock
    implements _i3.GuidedMeditationProgramRepository {
  MockGuidedMeditationProgramRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CustomError get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _FakeCustomError_0(
          this,
          Invocation.getter(#error),
        ),
      ) as _i2.CustomError);

  @override
  void sendOpenScreenEvent() => super.noSuchMethod(
        Invocation.method(
          #sendOpenScreenEvent,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> requestRegisterMeditateCompleted(int? time) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestRegisterMeditateCompleted,
          [time],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [AppRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppRouter extends _i1.Mock implements _i5.AppRouter {
  MockAppRouter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i6.AutoRoute> get routes => (super.noSuchMethod(
        Invocation.getter(#routes),
        returnValue: <_i6.AutoRoute>[],
      ) as List<_i6.AutoRoute>);

  @override
  void goToReplace(_i6.PageRouteInfo<dynamic>? route) => super.noSuchMethod(
        Invocation.method(
          #goToReplace,
          [route],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void goTo(
    _i6.PageRouteInfo<dynamic>? route, {
    _i5.OnCloseRoute? onClose,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #goTo,
          [route],
          {#onClose: onClose},
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [GuidedMeditationProgramViewContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockGuidedMeditationProgramViewContract extends _i1.Mock
    implements _i7.GuidedMeditationProgramViewContract {
  MockGuidedMeditationProgramViewContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void showLoading() => super.noSuchMethod(
        Invocation.method(
          #showLoading,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showNormalState() => super.noSuchMethod(
        Invocation.method(
          #showNormalState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showError(String? message) => super.noSuchMethod(
        Invocation.method(
          #showError,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void meditationCompleted() => super.noSuchMethod(
        Invocation.method(
          #meditationCompleted,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
