name: cinco_minutos_meditacao
description: A new Flutter project.
publish_to: 'none'

version: 4.13.7+68

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  google_sign_in: ^6.1.4
  flutter_dotenv: ^5.1.0
  firebase_analytics: ^11.0.0
  firebase_crashlytics: ^4.0.0
  get_it: ^7.6.0
  auto_route: ^8.1.3
  intl: ^0.19.0
  mockito: ^5.4.2
  device_info_plus: ^9.1.2
  firebase_performance: ^0.10.0
  flutter_svg: ^2.0.7
  flutter_facebook_auth: ^7.0.0
  retrofit_generator: ^8.1.0
  dio: ^5.4.3+1
  curl_logger_dio_interceptor: ^1.0.0
  json_annotation: ^4.9.0
  retrofit: ^4.1.0
  flutter_secure_storage: ^9.2.2
  convenient_test: ^1.3.7
  image_picker: ^1.1.2
  camera: ^0.11.0+1
  url_launcher: ^6.3.0
  audioplayers: ^6.0.0
  just_audio: ^0.9.39
  device_calendar: ^4.3.2
  timezone: ^0.9.4
  manage_calendar_events: ^2.0.3
  add_2_calendar: ^3.0.1
  youtube_player_flutter: ^8.0.0
  table_calendar: ^3.1.2
  flutter_image_compress: ^2.3.0
  datepicker_dropdown: ^0.1.5
  dropdown_button2: ^2.3.9
  social_share: ^2.3.1
  path_provider: ^2.1.5
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  wakelock_plus: ^1.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_flavorizr: ^2.2.1
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.8.0
  firebase_core_platform_interface: ^5.1.0

flutter:

  generate: true

  uses-material-design: true

  assets:
    - .env.dev
    - .env
    - assets/images/
    - assets/images/gifs/
    - assets/images/icons/
    - assets/audios/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Apertura
      fonts:
        - asset: assets/fonts/Apertura-MediumCondensed.otf
    - family: Heebo
      fonts:
        - asset: assets/fonts/heebo/Heebo-Regular.ttf
        - asset: assets/fonts/heebo/Heebo-Bold.ttf
          weight: 700
    - family: Blanch
      fonts:
        - asset: assets/fonts/BLANCH-CAPS.OTF
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
