name: cinco_minutos_meditacao
description: A new Flutter project.
publish_to: 'none'

version: 1.2.1+2

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  google_sign_in: ^6.1.4
  flutter_dotenv: ^5.1.0
  firebase_analytics: ^10.4.4
  firebase_crashlytics: ^3.3.4
  get_it: ^7.6.0
  auto_route: ^7.8.0
  intl: ^0.18.0
  mockito: ^5.4.2
  flutter_native_splash: ^2.3.2
  device_info_plus: ^9.0.3
  firebase_performance: ^0.9.2+5
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_flavorizr: ^2.2.1
  auto_route_generator: ^7.3.0
  build_runner: ^2.4.6

flutter:

  uses-material-design: true

  assets:
    - .env.dev
    - .env
    - assets/images/
    - assets/images/gifs/
    - assets/images/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
