// Mocks generated by Mockito 5.4.2 from annotations
// in cinco_minutos_meditacao/test/modules/authentication/login/login_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cinco_minutos_meditacao/modules/authentication/screens/login/login_presenter.dart'
    as _i2;
import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LoginPresenter].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginPresenter extends _i1.Mock implements _i2.LoginPresenter {
  MockLoginPresenter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<(_i4.User?, dynamic)> loginGoogle() => (super.noSuchMethod(
        Invocation.method(
          #loginGoogle,
          [],
        ),
        returnValue: _i3.Future<(_i4.User?, dynamic)>.value((null, null)),
      ) as _i3.Future<(_i4.User?, dynamic)>);
  @override
  void goToHome() => super.noSuchMethod(
        Invocation.method(
          #goToHome,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onOpenScreen() => super.noSuchMethod(
        Invocation.method(
          #onOpenScreen,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
