// Mocks generated by Mockito 5.4.4 from annotations
// in cinco_minutos_meditacao/test/modules/authentication/login/login_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:cinco_minutos_meditacao/core/analytics/event.dart' as _i4;
import 'package:cinco_minutos_meditacao/core/analytics/manager.dart' as _i3;
import 'package:cinco_minutos_meditacao/core/wrappers/secure_storage.dart'
    as _i9;
import 'package:cinco_minutos_meditacao/shared/clients/client_api.dart' as _i5;
import 'package:cinco_minutos_meditacao/shared/clients/models/auth_request.dart'
    as _i8;
import 'package:cinco_minutos_meditacao/shared/clients/models/authenticate_google_request.dart'
    as _i7;
import 'package:cinco_minutos_meditacao/shared/clients/models/authenticate_google_response.dart'
    as _i2;
import 'package:cinco_minutos_meditacao/shared/models/error.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthenticateGoogleResponse_0 extends _i1.SmartFake
    implements _i2.AuthenticateGoogleResponse {
  _FakeAuthenticateGoogleResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AnalyticsManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsManager extends _i1.Mock implements _i3.AnalyticsManager {
  MockAnalyticsManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void sendEvent(_i4.AnalyticsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #sendEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ClientApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientApi extends _i1.Mock implements _i5.ClientApi {
  MockClientApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.AuthenticateGoogleResponse> authGoogle(
          _i7.AuthenticateGoogleRequest? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #authGoogle,
          [token],
        ),
        returnValue: _i6.Future<_i2.AuthenticateGoogleResponse>.value(
            _FakeAuthenticateGoogleResponse_0(
          this,
          Invocation.method(
            #authGoogle,
            [token],
          ),
        )),
      ) as _i6.Future<_i2.AuthenticateGoogleResponse>);

  @override
  _i6.Future<void> login(_i8.AuthRequest? body) => (super.noSuchMethod(
        Invocation.method(
          #login,
          [body],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [SecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorage extends _i1.Mock implements _i9.SecureStorage {
  MockSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String> get tokenAPI => (super.noSuchMethod(
        Invocation.getter(#tokenAPI),
        returnValue: _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.getter(#tokenAPI),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<bool> get isLogged => (super.noSuchMethod(
        Invocation.getter(#isLogged),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<dynamic> setAllToNull() => (super.noSuchMethod(
        Invocation.method(
          #setAllToNull,
          [],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<void> setTokenAPI(String? tokenAPI) => (super.noSuchMethod(
        Invocation.method(
          #setTokenAPI,
          [tokenAPI],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setIsLogged(bool? isLogged) => (super.noSuchMethod(
        Invocation.method(
          #setIsLogged,
          [isLogged],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [CustomError].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomError extends _i1.Mock implements _i11.CustomError {
  MockCustomError() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set message(String? _message) => super.noSuchMethod(
        Invocation.setter(
          #message,
          _message,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set code(_i11.ErrorCodes? _code) => super.noSuchMethod(
        Invocation.setter(
          #code,
          _code,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set stackTrace(StackTrace? _stackTrace) => super.noSuchMethod(
        Invocation.setter(
          #stackTrace,
          _stackTrace,
        ),
        returnValueForMissingStub: null,
      );
}
