// Mocks generated by Mockito 5.4.4 from annotations
// in cinco_minutos_meditacao/test/modules/calendar/screens/calendar/calendar_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:cinco_minutos_meditacao/core/environment/manager.dart' as _i2;
import 'package:cinco_minutos_meditacao/modules/calendar/screens/calendar/calendar_contract.dart'
    as _i5;
import 'package:cinco_minutos_meditacao/modules/calendar/screens/calendar/calendar_model.dart'
    as _i3;
import 'package:cinco_minutos_meditacao/modules/calendar/screens/calendar/calendar_presenter.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEnvironmentManager_0 extends _i1.SmartFake
    implements _i2.EnvironmentManager {
  _FakeEnvironmentManager_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCalendarModel_1 extends _i1.SmartFake implements _i3.CalendarModel {
  _FakeCalendarModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CalendarPresenter].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarPresenter extends _i1.Mock implements _i4.CalendarPresenter {
  MockCalendarPresenter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set view(_i5.CalendarViewContract? _view) => super.noSuchMethod(
        Invocation.setter(
          #view,
          _view,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.EnvironmentManager get environmentManager => (super.noSuchMethod(
        Invocation.getter(#environmentManager),
        returnValue: _FakeEnvironmentManager_0(
          this,
          Invocation.getter(#environmentManager),
        ),
      ) as _i2.EnvironmentManager);

  @override
  _i3.CalendarModel get model => (super.noSuchMethod(
        Invocation.getter(#model),
        returnValue: _FakeCalendarModel_1(
          this,
          Invocation.getter(#model),
        ),
      ) as _i3.CalendarModel);

  @override
  set model(_i3.CalendarModel? _model) => super.noSuchMethod(
        Invocation.setter(
          #model,
          _model,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onOpenScreen() => super.noSuchMethod(
        Invocation.method(
          #onOpenScreen,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> initPresenter() => (super.noSuchMethod(
        Invocation.method(
          #initPresenter,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateImageProfile() => (super.noSuchMethod(
        Invocation.method(
          #updateImageProfile,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.CalendarModel> getCalendar(
    String? date,
    _i3.CalendarType? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCalendar,
          [
            date,
            type,
          ],
        ),
        returnValue: _i6.Future<_i3.CalendarModel>.value(_FakeCalendarModel_1(
          this,
          Invocation.method(
            #getCalendar,
            [
              date,
              type,
            ],
          ),
        )),
      ) as _i6.Future<_i3.CalendarModel>);

  @override
  _i6.Future<void> goToSocialShare(String? calendarType) => (super.noSuchMethod(
        Invocation.method(
          #goToSocialShare,
          [calendarType],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
