# frozen_string_literal: true

source "https://rubygems.org"

gem 'logger'
gem 'mutex_m'
gem 'abbrev'
gem 'cocoapods'
gem "fastlane"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
