// Mocks generated by Mockito 5.4.4 from annotations
// in cinco_minutos_meditacao/test/modules/meditate/in_your_time/in_your_time_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:io' as _i14;

import 'package:cinco_minutos_meditacao/core/analytics/event.dart' as _i9;
import 'package:cinco_minutos_meditacao/core/analytics/manager.dart' as _i8;
import 'package:cinco_minutos_meditacao/core/wrappers/secure_storage.dart'
    as _i18;
import 'package:cinco_minutos_meditacao/shared/clients/client_api.dart' as _i10;
import 'package:cinco_minutos_meditacao/shared/clients/models/requests/auth_request.dart'
    as _i13;
import 'package:cinco_minutos_meditacao/shared/clients/models/requests/authenticate_google_request.dart'
    as _i12;
import 'package:cinco_minutos_meditacao/shared/clients/models/requests/create_new_meditations_request.dart'
    as _i15;
import 'package:cinco_minutos_meditacao/shared/clients/models/responses/authenticate_google_response.dart'
    as _i2;
import 'package:cinco_minutos_meditacao/shared/clients/models/responses/meditations_response.dart'
    as _i5;
import 'package:cinco_minutos_meditacao/shared/clients/models/responses/register_response.dart'
    as _i3;
import 'package:cinco_minutos_meditacao/shared/clients/models/responses/user_response.dart'
    as _i4;
import 'package:cinco_minutos_meditacao/shared/clients/models/responses/week_calendar_response.dart'
    as _i6;
import 'package:cinco_minutos_meditacao/shared/models/error.dart' as _i7;
import 'package:dio/dio.dart' as _i17;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthenticateGoogleResponse_0 extends _i1.SmartFake
    implements _i2.AuthenticateGoogleResponse {
  _FakeAuthenticateGoogleResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRegisterResponse_1 extends _i1.SmartFake
    implements _i3.RegisterResponse {
  _FakeRegisterResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserResponse_2 extends _i1.SmartFake implements _i4.UserResponse {
  _FakeUserResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMeditationsResponse_3 extends _i1.SmartFake
    implements _i5.MeditationsResponse {
  _FakeMeditationsResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWeekCalendarResponse_4 extends _i1.SmartFake
    implements _i6.WeekCalendarResponse {
  _FakeWeekCalendarResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCustomError_5 extends _i1.SmartFake implements _i7.CustomError {
  _FakeCustomError_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AnalyticsManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsManager extends _i1.Mock implements _i8.AnalyticsManager {
  MockAnalyticsManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void sendEvent(_i9.AnalyticsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #sendEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ClientApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientApi extends _i1.Mock implements _i10.ClientApi {
  MockClientApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i2.AuthenticateGoogleResponse> authGoogle(
          _i12.AuthenticateGoogleRequest? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #authGoogle,
          [token],
        ),
        returnValue: _i11.Future<_i2.AuthenticateGoogleResponse>.value(
            _FakeAuthenticateGoogleResponse_0(
          this,
          Invocation.method(
            #authGoogle,
            [token],
          ),
        )),
      ) as _i11.Future<_i2.AuthenticateGoogleResponse>);

  @override
  _i11.Future<_i3.RegisterResponse> login(_i13.AuthRequest? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [body],
        ),
        returnValue:
            _i11.Future<_i3.RegisterResponse>.value(_FakeRegisterResponse_1(
          this,
          Invocation.method(
            #login,
            [body],
          ),
        )),
      ) as _i11.Future<_i3.RegisterResponse>);

  @override
  _i11.Future<_i3.RegisterResponse> register(_i13.AuthRequest? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [body],
        ),
        returnValue:
            _i11.Future<_i3.RegisterResponse>.value(_FakeRegisterResponse_1(
          this,
          Invocation.method(
            #register,
            [body],
          ),
        )),
      ) as _i11.Future<_i3.RegisterResponse>);

  @override
  _i11.Future<_i4.UserResponse> user() => (super.noSuchMethod(
        Invocation.method(
          #user,
          [],
        ),
        returnValue: _i11.Future<_i4.UserResponse>.value(_FakeUserResponse_2(
          this,
          Invocation.method(
            #user,
            [],
          ),
        )),
      ) as _i11.Future<_i4.UserResponse>);

  @override
  _i11.Future<dynamic> uploadPhoto(_i14.File? photo) => (super.noSuchMethod(
        Invocation.method(
          #uploadPhoto,
          [photo],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);

  @override
  _i11.Future<_i5.MeditationsResponse> meditations() => (super.noSuchMethod(
        Invocation.method(
          #meditations,
          [],
        ),
        returnValue: _i11.Future<_i5.MeditationsResponse>.value(
            _FakeMeditationsResponse_3(
          this,
          Invocation.method(
            #meditations,
            [],
          ),
        )),
      ) as _i11.Future<_i5.MeditationsResponse>);

  @override
  _i11.Future<_i5.MeditationsResponse> meditationsByUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #meditationsByUser,
          [userId],
        ),
        returnValue: _i11.Future<_i5.MeditationsResponse>.value(
            _FakeMeditationsResponse_3(
          this,
          Invocation.method(
            #meditationsByUser,
            [userId],
          ),
        )),
      ) as _i11.Future<_i5.MeditationsResponse>);

  @override
  _i11.Future<void> createNewMeditation(
          _i15.CreateNewMeditationsRequest? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNewMeditation,
          [body],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<_i6.WeekCalendarResponse> calendarWeek(String? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #calendarWeek,
          [date],
        ),
        returnValue: _i11.Future<_i6.WeekCalendarResponse>.value(
            _FakeWeekCalendarResponse_4(
          this,
          Invocation.method(
            #calendarWeek,
            [date],
          ),
        )),
      ) as _i11.Future<_i6.WeekCalendarResponse>);
}

/// A class which mocks [CustomError].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomError extends _i1.Mock implements _i7.CustomError {
  MockCustomError() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set message(String? _message) => super.noSuchMethod(
        Invocation.setter(
          #message,
          _message,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set code(_i7.ErrorCodes? _code) => super.noSuchMethod(
        Invocation.setter(
          #code,
          _code,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set stackTrace(StackTrace? _stackTrace) => super.noSuchMethod(
        Invocation.setter(
          #stackTrace,
          _stackTrace,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get getErrorMessage => (super.noSuchMethod(
        Invocation.getter(#getErrorMessage),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.getter(#getErrorMessage),
        ),
      ) as String);

  @override
  _i7.CustomError sendErrorToCrashlytics({
    String? message,
    _i7.ErrorCodes? code,
    StackTrace? stackTrace,
    _i17.DioException? dioException,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendErrorToCrashlytics,
          [],
          {
            #message: message,
            #code: code,
            #stackTrace: stackTrace,
            #dioException: dioException,
          },
        ),
        returnValue: _FakeCustomError_5(
          this,
          Invocation.method(
            #sendErrorToCrashlytics,
            [],
            {
              #message: message,
              #code: code,
              #stackTrace: stackTrace,
              #dioException: dioException,
            },
          ),
        ),
      ) as _i7.CustomError);
}

/// A class which mocks [SecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorage extends _i1.Mock implements _i18.SecureStorage {
  MockSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<String> get tokenAPI => (super.noSuchMethod(
        Invocation.getter(#tokenAPI),
        returnValue: _i11.Future<String>.value(_i16.dummyValue<String>(
          this,
          Invocation.getter(#tokenAPI),
        )),
      ) as _i11.Future<String>);

  @override
  _i11.Future<bool> get isLogged => (super.noSuchMethod(
        Invocation.getter(#isLogged),
        returnValue: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);

  @override
  _i11.Future<String> get userId => (super.noSuchMethod(
        Invocation.getter(#userId),
        returnValue: _i11.Future<String>.value(_i16.dummyValue<String>(
          this,
          Invocation.getter(#userId),
        )),
      ) as _i11.Future<String>);

  @override
  _i11.Future<String> get userName => (super.noSuchMethod(
        Invocation.getter(#userName),
        returnValue: _i11.Future<String>.value(_i16.dummyValue<String>(
          this,
          Invocation.getter(#userName),
        )),
      ) as _i11.Future<String>);

  @override
  _i11.Future<String> get userEmail => (super.noSuchMethod(
        Invocation.getter(#userEmail),
        returnValue: _i11.Future<String>.value(_i16.dummyValue<String>(
          this,
          Invocation.getter(#userEmail),
        )),
      ) as _i11.Future<String>);

  @override
  _i11.Future<String> get googleId => (super.noSuchMethod(
        Invocation.getter(#googleId),
        returnValue: _i11.Future<String>.value(_i16.dummyValue<String>(
          this,
          Invocation.getter(#googleId),
        )),
      ) as _i11.Future<String>);

  @override
  _i11.Future<String> get profilePhoto => (super.noSuchMethod(
        Invocation.getter(#profilePhoto),
        returnValue: _i11.Future<String>.value(_i16.dummyValue<String>(
          this,
          Invocation.getter(#profilePhoto),
        )),
      ) as _i11.Future<String>);

  @override
  _i11.Future<dynamic> setAllToNull() => (super.noSuchMethod(
        Invocation.method(
          #setAllToNull,
          [],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);

  @override
  _i11.Future<void> setTokenAPI(String? tokenAPI) => (super.noSuchMethod(
        Invocation.method(
          #setTokenAPI,
          [tokenAPI],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setIsLogged(bool? isLogged) => (super.noSuchMethod(
        Invocation.method(
          #setIsLogged,
          [isLogged],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setUserId(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #setUserId,
          [userId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setUserName(String? userName) => (super.noSuchMethod(
        Invocation.method(
          #setUserName,
          [userName],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setUserEmail(String? userEmail) => (super.noSuchMethod(
        Invocation.method(
          #setUserEmail,
          [userEmail],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setGoogleId(String? googleId) => (super.noSuchMethod(
        Invocation.method(
          #setGoogleId,
          [googleId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setProfilePhoto(String? profilePhoto) =>
      (super.noSuchMethod(
        Invocation.method(
          #setProfilePhoto,
          [profilePhoto],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
}
