// Mocks generated by Mockito 5.4.4 from annotations
// in cinco_minutos_meditacao/test/modules/meditate/five_minutes/five_minutes_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cinco_minutos_meditacao/modules/meditate/screens/five_minutes/five_minutes_contract.dart'
    as _i3;
import 'package:cinco_minutos_meditacao/modules/meditate/screens/five_minutes/five_minutes_presenter.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FiveMinutesPresenter].
///
/// See the documentation for Mockito's code generation for more information.
class MockFiveMinutesPresenter extends _i1.Mock
    implements _i2.FiveMinutesPresenter {
  MockFiveMinutesPresenter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set view(_i3.FiveMinutesViewContract? _view) => super.noSuchMethod(
        Invocation.setter(
          #view,
          _view,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onOpenScreen() => super.noSuchMethod(
        Invocation.method(
          #onOpenScreen,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void goToMeditateInfo() => super.noSuchMethod(
        Invocation.method(
          #goToMeditateInfo,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> submitMeditateCompleted(int? time) => (super.noSuchMethod(
        Invocation.method(
          #submitMeditateCompleted,
          [time],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void goToShare() => super.noSuchMethod(
        Invocation.method(
          #goToShare,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
