# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Deploy a new version to the Google Play Internal Test"
  lane :internal_test do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(track: 'internal')
  end

  desc "Upload dev app to Firebase App Distribution"
  lane :firebase do
    firebase_app_distribution(
      app: "1:106395996253:android:91b47db80ae6b71503bdb4",
      groups: "testers",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-dev-debug.apk",
      firebase_cli_token: ENV['FIREBASE_TOKEN'],
      service_credentials_file: "../android/app/src/dev/google-service-account.json",
    )
  end

  desc "Upload dev app to Firebase App Distribution"
  lane :firebase_prod do
    firebase_app_distribution(
      app: "1:106395996253:android:aae5cc5b4f1811e303bdb4",
      groups: "testers",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-prod-debug.apk",
      firebase_cli_token: ENV['FIREBASE_TOKEN'],
    )
  end

  desc "Upload production app to Play Store"
  lane :upload_android_production_app do
      upload_to_play_store(
          package_name: "com.polvo.cincominutos",
          json_key: "fastlane/minutos-3ae7f-fde6e0b502d4.json",
          skip_upload_apk: true,
          track: 'internal',
          aab: "../build/app/outputs/bundle/storeRelease/app-store-release.aab",
      )
  end
end
