// Mocks generated by Mockito 5.4.4 from annotations
// in cinco_minutos_meditacao/test/modules/authentication/screens/welcome/welcome_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cinco_minutos_meditacao/core/analytics/event.dart' as _i3;
import 'package:cinco_minutos_meditacao/core/analytics/manager.dart' as _i2;
import 'package:cinco_minutos_meditacao/core/wrappers/secure_storage.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AnalyticsManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsManager extends _i1.Mock implements _i2.AnalyticsManager {
  MockAnalyticsManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void sendEvent(_i3.AnalyticsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #sendEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorage extends _i1.Mock implements _i4.SecureStorage {
  MockSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> get tokenAPI => (super.noSuchMethod(
        Invocation.getter(#tokenAPI),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.getter(#tokenAPI),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<bool> get isLogged => (super.noSuchMethod(
        Invocation.getter(#isLogged),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<String> get userId => (super.noSuchMethod(
        Invocation.getter(#userId),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.getter(#userId),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> get userName => (super.noSuchMethod(
        Invocation.getter(#userName),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.getter(#userName),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> get userEmail => (super.noSuchMethod(
        Invocation.getter(#userEmail),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.getter(#userEmail),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> get googleId => (super.noSuchMethod(
        Invocation.getter(#googleId),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.getter(#googleId),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> get profilePhoto => (super.noSuchMethod(
        Invocation.getter(#profilePhoto),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.getter(#profilePhoto),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<dynamic> setAllToNull() => (super.noSuchMethod(
        Invocation.method(
          #setAllToNull,
          [],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Future<void> setTokenAPI(String? tokenAPI) => (super.noSuchMethod(
        Invocation.method(
          #setTokenAPI,
          [tokenAPI],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setIsLogged(bool? isLogged) => (super.noSuchMethod(
        Invocation.method(
          #setIsLogged,
          [isLogged],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setUserId(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #setUserId,
          [userId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setUserName(String? userName) => (super.noSuchMethod(
        Invocation.method(
          #setUserName,
          [userName],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setUserEmail(String? userEmail) => (super.noSuchMethod(
        Invocation.method(
          #setUserEmail,
          [userEmail],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setGoogleId(String? googleId) => (super.noSuchMethod(
        Invocation.method(
          #setGoogleId,
          [googleId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setProfilePhoto(String? profilePhoto) => (super.noSuchMethod(
        Invocation.method(
          #setProfilePhoto,
          [profilePhoto],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
