// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcejDEzpp4eYvt0HJnDU-CrM8ytSqSaJI',
    appId: '1:106395996253:android:91b47db80ae6b71503bdb4',
    messagingSenderId: '106395996253',
    projectId: 'minutos-3ae7f',
    storageBucket: 'minutos-3ae7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASSIopeAw71gLaEsXpNYEMHOASPctD5IQ',
    appId: '1:106395996253:ios:06758a688913c30903bdb4',
    messagingSenderId: '106395996253',
    projectId: 'minutos-3ae7f',
    storageBucket: 'minutos-3ae7f.appspot.com',
    androidClientId:
        '106395996253-08bcto7ojojf3aqhnosen8l2dfvq4p8e.apps.googleusercontent.com',
    iosClientId:
        '106395996253-pg9od22vi9o6m7bsr9lt98k7c6rki4l5.apps.googleusercontent.com',
    iosBundleId: 'eumedito.org.cincoMinutosMeditacao',
  );
}
