name: Android distribution Dev

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    permissions:
      checks: write
      contents: write
      packages: write
    runs-on: [marcOS]

    steps:
      - name: Efetua checkout da branch
        uses: actions/checkout@v3

#      - name: Setup Ruby
#        uses: actions/setup-ruby@v1
#        with:
#          ruby-version: 2.7

#      - name: Install SSH key
#        uses: shimataro/ssh-key-action@v2
#        with:
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          name: id_rsa
#          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Setup Fastlane
        run: |
          cd android
          bundle install

#      - name: Setup Java
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin' # See 'Supported distributions' for available options
#          java-version: '17'

#      - name: Setup flutter e builda projeto
#        uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '3.10.6'
#          channel: 'stable'
#          token: ${{ secrets.GITHUB_TOKEN }}
#      - run: flutter --version
#      - run: flutter pub get
#      - run: ./localization
#      - run: flutter packages pub run build_runner build --delete-conflicting-outputs
#      - run: flutter build ipa --export-options-plist ios/export/info_dev.plist --flavor dev -t lib/core/flavors/main_dev.dart -v

      - name: Setup flutter e builda projeto
        run: |
          flutter clean
          flutter pub get
          ./localization
          flutter packages pub run build_runner build --delete-conflicting-outputs
          flutter build apk --debug --flavor dev -t lib/core/flavors/main_dev.dart 

      - name: Upload do apk
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-dev-debug.apk

  firebase:
    needs: build
    permissions:
      checks: write
      contents: write
      packages: write
    runs-on: [ marcOS ]

    steps:
      - name: Download apk
        uses: actions/download-artifact@v3
        with:
          name: apk
          path: build/app/outputs/flutter-apk

      - name: Deploy do firebase
        run: |
          ls -la build/app/outputs/flutter-apk
          cd android
          bundle exec fastlane firebase
        env:
          FIREBASE_TESTER_GROUPS: ${{ secrets.FIREBASE_TESTER_GROUPS }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
