name: Android distribution Store

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    permissions:
      checks: write
      contents: write
      packages: write
    runs-on: ubuntu-latest  # Alterado para ubuntu-latest

    steps:
      - name: Efetua checkout da branch
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Setup Fastlane
        run: |
          cd android
          echo "gem 'ostruct'" >> Gemfile
          gem install bundler:2.4.19
          bundle install

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode and save the keystore file
        run: |
          echo "${{ secrets.ANDROID_STORE_FILE }}" | base64 --decode > /tmp/KeyStorePlay.keystore
          echo "${{ secrets.JSON_KEY }}" | base64 --decode > $GITHUB_WORKSPACE/android/fastlane/minutos-3ae7f-fde6e0b502d4.json
        env:
          ANDROID_STORE_FILE: ${{ secrets.ANDROID_STORE_FILE }}
          JSON_KEY: ${{ secrets.JSON_KEY }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build projeto LOCALMENTE
        run: |
          flutter clean
          flutter pub get
          ./localization
          flutter packages pub run build_runner build --delete-conflicting-outputs
          flutter build appbundle --release --flavor store -t lib/core/flavors/main_prod.dart
        env:
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
          ANDROID_STORE_FILE: /tmp/KeyStorePlay.keystore

      - name: Deploy do Google Play Store
        run: |
          ls -la build/app/outputs/bundle/storeRelease
          cd android
          bundle exec fastlane upload_android_production_app
        env:
          JSON_KEY: ${{ secrets.JSON_KEY }}