name: Android distribution Development LOCAL

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    permissions:
      checks: write
      contents: write
      packages: write
    runs-on: [ marcOS ]

    steps:
      - name: Efetua checkout da branch
        uses: actions/checkout@v3

      - name: Setup Fastlane
        run: |
          cd android
          bundle install

      - name: Setup flutter e builda projeto LOCALMENTE
        run: |
          flutter clean
          flutter pub get
          ./localization
          flutter packages pub run build_runner build --delete-conflicting-outputs
          flutter build apk --debug --flavor dev -t lib/core/flavors/main_dev.dart
        env:
          JAVA_HOME: /opt/homebrew/opt/openjdk@17

      - name: Deploy do firebase
        run: |
          ls -la build/app/outputs/flutter-apk
          cd android
          bundle exec fastlane firebase
        env:
          FIREBASE_TESTER_GROUPS: ${{ secrets.FIREBASE_TESTER_GROUPS }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
