name: Android distribution Store LOCAL

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    permissions:
      checks: write
      contents: write
      packages: write
    runs-on: [ marcOS ]

    steps:
      - name: Efetua checkout da branch
        uses: actions/checkout@v3

      - name: Setup Fastlane
        run: |
          cd android
          bundle install

      - name: Setup flutter e builda projeto LOCALMENTE
        run: |
          flutter clean
          flutter pub get
          ./localization
          flutter packages pub run build_runner build --delete-conflicting-outputs
          flutter build appbundle --no-tree-shake-icons --release --flavor store -t lib/core/flavors/main_prod.dart -v

      - name: Deploy do Google Play Store
        run: |
          ls -la build/app/outputs/bundle/storeRelease
          cd android
          bundle exec fastlane upload_android_production_app
        env:
          JSON_KEY: ${{ secrets.JSON_KEY }}
