name: Firebase Distribution

on:
  release:
    types: [published]

jobs:
  flutter_test:
    if: "github.event.release.prerelease"
    name: Flutter Tests
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      packages: write
    steps:
      - name: Efetua checkout da branch
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup flutter e builda projeto
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze --no-fatal-infos --no-fatal-warnings
      - run: dart format lib/ --set-exit-if-changed
      - run: dart format test/ --set-exit-if-changed
      - run: flutter test --coverage
      - run: flutter test --machine > test-results.json
      - uses: dorny/test-reporter@v1.6.0
        with:
          name: Flutter results
          path: test-results.json
          reporter: flutter-json
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verifica o coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2.1.0
        with:
          min_coverage: 50

  build_appbundle:
    if: "github.event.release.prerelease"
    name: Build Flutter (Android)
    needs: flutter_test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      packages: write
    steps:
      - name: Efetua checkout da branch
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup flutter e builda projeto
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
          channel: 'stable'
      - run: flutter doctor
      - run: flutter clean
      - run: flutter pub get
      - run: ./localization
      - run: dart packages pub run build_runner build --delete-conflicting-outputs
      - run: flutter build apk --release --flavor prod -t lib/core/flavors/main_prod.dart -v

      - name: Upload do APK para o firebase app distribution
        uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: build/app/outputs/flutter-apk/app-prod-release.apk

      - name: Upload a Build Artifact to Firebase app distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: build/app/outputs/flutter-apk/app-prod-release.apk

