name: Distribution DEV

on:
  workflow_dispatch:

jobs:
  tests:
    uses: polvo-labs/cincominutos-app/.github/workflows/tests.yaml@main

  ios-distribution-dev:
    needs: tests
    uses: polvo-labs/cincominutos-app/.github/workflows/ios_distribution_dev.yaml@main
    secrets: inherit

  android-distribution-dev:
    needs: tests
    uses: polvo-labs/cincominutos-app/.github/workflows/android_distribution_dev.yaml@main
    secrets: inherit