name: Distribution LOCAL

on:
  workflow_dispatch:

jobs:
  tests:
    uses: polvo-labs/cincominutos-app/.github/workflows/tests_local.yaml@main

  ios_distribution_local:
    needs: tests
    uses: polvo-labs/cincominutos-app/.github/workflows/ios_distribution_local.yaml@main

  android_distribution_local:
    needs: tests
    uses: polvo-labs/cincominutos-app/.github/workflows/android_distribution_local.yaml@main

  pre-release:
    needs: [ ios_distribution_local, android_distribution_local ]
    permissions:
      checks: write
      contents: write
      packages: write
    runs-on: [ marcOS ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ### O que foi feito?
            - First Change
            - Second Change
          draft: true
          prerelease: true