name: CI Tests

on:
  workflow_dispatch:

  push:
    branches:

jobs:
  flutter_test:
    name: Flutter Tests
#    runs-on: ubuntu-latest
    runs-on: [marcOS]
    permissions:
      checks: write
      contents: write
      packages: write
    steps:
      - name: Efetua checkout da branch
        uses: actions/checkout@v3

#      - name: Setup Java
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin' # See 'Supported distributions' for available options
#          java-version: '17'

      - name: Setup flutter e builda projeto
#        uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '3.10.6'
#          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - run: ./localization
      - run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - run: flutter analyze --no-fatal-infos --no-fatal-warnings
      - run: dart format lib/ --set-exit-if-changed
      - run: dart format test/ --set-exit-if-changed
      - run: flutter test --coverage
      - run: flutter test --machine > test-results.json

      - name: Report result tests
        uses: dorny/test-reporter@v1.6.0
        with:
          name: Flutter results
          path: test-results.json
          reporter: flutter-json
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verifica o coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2.1.0
        with:
          min_coverage: 50