name: CI Tests

on:
  workflow_dispatch:
  workflow_call:

  push:
    branches:
      - '*'
      - '!main'

jobs:
  flutter_test:
    name: Flutter Tests
#    runs-on: [marcOS]
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      packages: write
    steps:
      - name: Efetua checkout da branch
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup flutter e builda projeto
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
          channel: 'stable'
      - run: |
          flutter --version
          flutter pub get
          ./localization
          flutter packages pub run build_runner build --delete-conflicting-outputs
          flutter analyze --no-fatal-infos --no-fatal-warnings
          flutter test --coverage
          sudo apt install libperlio-gzip-perl libjson-perl
          wget "https://github.com/linux-test-project/lcov/archive/master.zip"
          unzip "master.zip"
          cd "lcov-master"
          sudo make install
          cd ..
          lcov --remove coverage/lcov.info 'lib/core/*' -o coverage/new_lcov.info
          lcov --remove coverage/new_lcov.info '**/strings/localization/**' -o coverage/new2_lcov.info
          flutter test --machine > test-results.json

#      - name: Setup flutter e builda projeto LOCALMENTE
#        run: |
#          flutter --version
#          flutter pub get
#          ./localization
#          flutter packages pub run build_runner build --delete-conflicting-outputs
#          flutter analyze --no-fatal-infos --no-fatal-warnings
#          flutter test --coverage
#          lcov --remove coverage/lcov.info 'lib/core/*' -o coverage/new_lcov.info
#          lcov --remove coverage/new_lcov.info '**/strings/localization/**' -o coverage/new2_lcov.info
#          flutter test --machine > test-results.json

      - name: Report result tests
        uses: dorny/test-reporter@v1.6.0
        with:
          name: Flutter results
          path: test-results.json
          reporter: flutter-json
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verifica o coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2.1.0
        with:
          min_coverage: 70
          exclude: './lib/core/* **/strings/localization/**'
          path: ./coverage/new2_lcov.info